osx_image: xcode11.3
language: objective-c
xcode_project: workspace/GoogleMapsUtils.xcodeproj
xcode_scheme: GoogleMapsUtils
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone 8

#cache: cocoapods
#podfile: workspace/Podfile
#before_install:
#- gem install cocoapods
#- pod install --project-directory=workspace/

